version: '3'

services:
  hmall-mysql:
    image: mysql:8.0
    container_name: hmall-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mall
      MYSQL_USER: mall
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306


  hmall-redis:
    image: redis:6.2
    container_name: hmall-redis
    restart: always
    ports:
      - 6379:6379